import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * This file is used to define the sidebars for your docs.
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;