openapi: 3.0.0
info:
  title: Vector RAG Agent API
  description: API for the Vector Lab Assistant that provides RAG-based answers to textbook questions
  version: 1.0.0
servers:
  - url: https://api.physical-ai-handbook.com
    description: Production server
  - url: https://staging-api.physical-ai-handbook.com
    description: Staging server

paths:
  /api/v1/chat:
    post:
      summary: Send a message to the Vector agent
      description: Submit a user query to the Vector RAG agent and receive a contextual response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful response from the Vector agent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Invalid request format
        '429':
          description: Rate limit exceeded
      security:
        - bearerAuth: []

  /api/v1/translate:
    post:
      summary: Translate content between English and Urdu
      description: Translate textbook content between English and Urdu while preserving technical terms
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TranslateRequest'
      responses:
        '200':
          description: Successfully translated content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TranslateResponse'
        '400':
          description: Invalid request format or unsupported language

  /api/v1/hardware-check:
    post:
      summary: Check hardware compatibility
      description: Check if user's hardware meets requirements for specific textbook modules
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HardwareCheckRequest'
      responses:
        '200':
          description: Hardware compatibility assessment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HardwareCheckResponse'
        '400':
          description: Invalid request format

  /api/v1/user/profile:
    get:
      summary: Get user profile
      description: Retrieve the authenticated user's profile information
      responses:
        '200':
          description: User profile data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          description: Unauthorized - user not authenticated
      security:
        - bearerAuth: []
    put:
      summary: Update user profile
      description: Update the authenticated user's profile information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfileUpdate'
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          description: Unauthorized - user not authenticated
        '400':
          description: Invalid request format
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ChatRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: The user's question or message to the Vector agent
          example: "How do I create a ROS 2 publisher node?"
        context_chapter:
          type: string
          description: The current chapter ID for context awareness
          example: "module1-chapter2"
        user_hardware:
          type: string
          description: User's hardware specification for compatibility-aware responses
          example: "RTX 4090"

    ChatResponse:
      type: object
      required:
        - response
        - sources
        - is_context_aware
      properties:
        response:
          type: string
          description: The Vector agent's response to the query
          example: "To create a ROS 2 publisher node, you first need to import rclpy..."
        sources:
          type: array
          items:
            type: string
          description: List of textbook sections referenced in the response
          example: ["module1-chapter2", "module1-chapter3"]
        is_context_aware:
          type: boolean
          description: Whether the response was tailored to the current context
          example: true
        hardware_warning:
          type: string
          description: Any hardware compatibility warnings in the response
          example: "Note: This example requires an RTX GPU for Isaac Sim"

    TranslateRequest:
      type: object
      required:
        - text
        - target_language
      properties:
        text:
          type: string
          description: The text to translate
          example: "A ROS 2 node is an executable that uses ROS to communicate with other nodes."
        target_language:
          type: string
          description: The target language code (en, ur)
          example: "ur"
        preserve_technical_terms:
          type: boolean
          description: Whether to preserve English technical terms (default: true)
          example: true

    TranslateResponse:
      type: object
      required:
        - translated_text
        - source_language
        - target_language
      properties:
        translated_text:
          type: string
          description: The translated text
          example: "ROS 2 نوڈ ایک ایسا قابل عمل پروگرام ہے جو دیگر نوڈس سے رابطہ کرنے کے لیے ROS کا استعمال کرتا ہے۔"
        source_language:
          type: string
          description: The source language code
          example: "en"
        target_language:
          type: string
          description: The target language code
          example: "ur"

    HardwareCheckRequest:
      type: object
      required:
        - hardware_spec
        - module_requirement
      properties:
        hardware_spec:
          type: string
          description: User's hardware specification
          example: "MacBook Pro M1"
        module_requirement:
          type: string
          description: The module or component being checked
          example: "Isaac Sim"

    HardwareCheckResponse:
      type: object
      required:
        - is_compatible
        - compatibility_score
        - recommendations
      properties:
        is_compatible:
          type: boolean
          description: Whether the hardware meets minimum requirements
          example: false
        compatibility_score:
          type: number
          description: Compatibility score from 0 to 100
          example: 30
        recommendations:
          type: string
          description: Recommendations for the user
          example: "Isaac Sim requires an RTX GPU with at least 12GB VRAM. Consider using a cloud lab."

    UserProfile:
      type: object
      required:
        - user_id
        - email
      properties:
        user_id:
          type: string
          description: Unique identifier for the user
          example: "usr_1234567890"
        email:
          type: string
          description: User's email address
          example: "student@example.com"
        gpu_model:
          type: string
          description: User's GPU model
          example: "RTX 4090"
        programming_level:
          type: string
          description: User's programming experience level
          enum: [beginner, intermediate, advanced]
          example: "intermediate"
        preferred_language:
          type: string
          description: User's preferred language
          example: "en"
        created_at:
          type: string
          format: date-time
          description: Account creation timestamp
          example: "2025-12-10T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: Last profile update timestamp
          example: "2025-12-10T10:00:00Z"

    UserProfileUpdate:
      type: object
      properties:
        gpu_model:
          type: string
          description: User's GPU model
          example: "RTX 4090"
        programming_level:
          type: string
          description: User's programming experience level
          enum: [beginner, intermediate, advanced]
          example: "intermediate"
        preferred_language:
          type: string
          description: User's preferred language
          example: "ur"